namespace ProMag_Steam_Games
{
    partial class Form1
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            panelLeft = new Panel();
            btnLogout = new Button();
            btnSettings = new Button();
            btnHistory = new Button();
            btnPackages = new Button();
            btnAllGames = new Button();
            panelLogin = new Panel();
            chkRememberMe = new CheckBox();
            btnRegister = new Button();
            btnLogin = new Button();
            txtPassword = new TextBox();
            txtUsername = new TextBox();
            labelStatus = new Label();
            labelWelcome = new Label();
            labelMessage = new Label();
            panelLeft.SuspendLayout();
            panelLogin.SuspendLayout();
            SuspendLayout();
            panelLeft.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left;
            panelLeft.BackColor = Color.DimGray;
            panelLeft.Controls.Add(btnLogout);
            panelLeft.Controls.Add(btnSettings);
            panelLeft.Controls.Add(btnHistory);
            panelLeft.Controls.Add(btnPackages);
            panelLeft.Controls.Add(btnAllGames);
            panelLeft.Location = new Point(0, 0);
            panelLeft.Name = "panelLeft";
            panelLeft.Size = new Size(150, 450);
            panelLeft.TabIndex = 2;
            btnLogout.BackColor = Color.FromArgb(0, 120, 215);
            btnLogout.FlatAppearance.BorderSize = 0;
            btnLogout.FlatStyle = FlatStyle.Flat;
            btnLogout.ForeColor = Color.White;
            btnLogout.Location = new Point(10, 210);
            btnLogout.Name = "btnLogout";
            btnLogout.Size = new Size(130, 40);
            btnLogout.TabIndex = 4;
            btnLogout.Text = "Logout";
            btnLogout.UseVisualStyleBackColor = false;
            btnLogout.Click += BtnLogout_Click;
            btnSettings.BackColor = Color.FromArgb(0, 120, 215);
            btnSettings.FlatAppearance.BorderSize = 0;
            btnSettings.FlatStyle = FlatStyle.Flat;
            btnSettings.ForeColor = Color.White;
            btnSettings.Location = new Point(10, 160);
            btnSettings.Name = "btnSettings";
            btnSettings.Size = new Size(130, 40);
            btnSettings.TabIndex = 0;
            btnSettings.Text = "Settings";
            btnSettings.UseVisualStyleBackColor = false;
            btnSettings.Click += BtnSettings_Click;
            btnHistory.BackColor = Color.FromArgb(0, 120, 215);
            btnHistory.FlatAppearance.BorderSize = 0;
            btnHistory.FlatStyle = FlatStyle.Flat;
            btnHistory.ForeColor = Color.White;
            btnHistory.Location = new Point(10, 110);
            btnHistory.Name = "btnHistory";
            btnHistory.Size = new Size(130, 40);
            btnHistory.TabIndex = 1;
            btnHistory.Text = "History";
            btnHistory.UseVisualStyleBackColor = false;
            btnHistory.Click += BtnHistory_Click;
            btnPackages.BackColor = Color.FromArgb(0, 120, 215);
            btnPackages.FlatAppearance.BorderSize = 0;
            btnPackages.FlatStyle = FlatStyle.Flat;
            btnPackages.ForeColor = Color.White;
            btnPackages.Location = new Point(10, 60);
            btnPackages.Name = "btnPackages";
            btnPackages.Size = new Size(130, 40);
            btnPackages.TabIndex = 2;
            btnPackages.Text = "Packages";
            btnPackages.UseVisualStyleBackColor = false;
            btnPackages.Click += BtnPackages_Click;
            btnAllGames.BackColor = Color.FromArgb(0, 120, 215);
            btnAllGames.FlatAppearance.BorderSize = 0;
            btnAllGames.FlatStyle = FlatStyle.Flat;
            btnAllGames.ForeColor = Color.White;
            btnAllGames.Location = new Point(10, 10);
            btnAllGames.Name = "btnAllGames";
            btnAllGames.Size = new Size(130, 40);
            btnAllGames.TabIndex = 3;
            btnAllGames.Text = "All Games";
            btnAllGames.UseVisualStyleBackColor = false;
            btnAllGames.Click += BtnAllGames_Click;
            panelLogin.Anchor = AnchorStyles.None;
            panelLogin.BackColor = Color.FromArgb(64, 64, 64);
            panelLogin.Controls.Add(chkRememberMe);
            panelLogin.Controls.Add(btnRegister);
            panelLogin.Controls.Add(btnLogin);
            panelLogin.Controls.Add(txtPassword);
            panelLogin.Controls.Add(txtUsername);
            panelLogin.Location = new Point(200, 100);
            panelLogin.Name = "panelLogin";
            panelLogin.Size = new Size(400, 200);
            panelLogin.TabIndex = 1;
            chkRememberMe.ForeColor = Color.White;
            chkRememberMe.Location = new Point(50, 170);
            chkRememberMe.Name = "chkRememberMe";
            chkRememberMe.Size = new Size(150, 20);
            chkRememberMe.TabIndex = 4;
            chkRememberMe.Text = "Remember Me";
            chkRememberMe.UseVisualStyleBackColor = true;
            btnRegister.BackColor = Color.FromArgb(0, 120, 215);
            btnRegister.FlatAppearance.BorderSize = 0;
            btnRegister.FlatStyle = FlatStyle.Flat;
            btnRegister.ForeColor = Color.White;
            btnRegister.Location = new Point(220, 120);
            btnRegister.Name = "btnRegister";
            btnRegister.Size = new Size(130, 40);
            btnRegister.TabIndex = 0;
            btnRegister.Text = "Register";
            btnRegister.UseVisualStyleBackColor = false;
            btnRegister.Click += BtnRegister_Click;
            btnLogin.BackColor = Color.FromArgb(0, 120, 215);
            btnLogin.FlatAppearance.BorderSize = 0;
            btnLogin.FlatStyle = FlatStyle.Flat;
            btnLogin.ForeColor = Color.White;
            btnLogin.Location = new Point(50, 120);
            btnLogin.Name = "btnLogin";
            btnLogin.Size = new Size(130, 40);
            btnLogin.TabIndex = 1;
            btnLogin.Text = "Login";
            btnLogin.UseVisualStyleBackColor = false;
            btnLogin.Click += BtnLogin_Click;
            txtPassword.BackColor = Color.FromArgb(100, 100, 100);
            txtPassword.ForeColor = Color.White;
            txtPassword.Location = new Point(50, 70);
            txtPassword.Name = "txtPassword";
            txtPassword.PasswordChar = '*';
            txtPassword.Size = new Size(300, 23);
            txtPassword.TabIndex = 2;
            txtUsername.BackColor = Color.FromArgb(100, 100, 100);
            txtUsername.ForeColor = Color.White;
            txtUsername.Location = new Point(50, 30);
            txtUsername.Name = "txtUsername";
            txtUsername.Size = new Size(300, 23);
            txtUsername.TabIndex = 3;
            labelStatus.ForeColor = Color.White;
            labelStatus.Location = new Point(156, 421);
            labelStatus.Name = "labelStatus";
            labelStatus.Size = new Size(224, 20);
            labelStatus.TabIndex = 0;
            labelStatus.Text = "Status: Not logged in";
            labelStatus.TextAlign = ContentAlignment.MiddleLeft;
            labelWelcome.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            labelWelcome.ForeColor = Color.White;
            labelWelcome.Location = new Point(167, 9);
            labelWelcome.Name = "labelWelcome";
            labelWelcome.Size = new Size(621, 30);
            labelWelcome.TabIndex = 5;
            labelWelcome.Text = "Welcome";
            labelWelcome.TextAlign = ContentAlignment.MiddleCenter;
            labelWelcome.Visible = false;
            labelMessage.ForeColor = Color.White;
            labelMessage.Location = new Point(156, 381);
            labelMessage.Name = "labelMessage";
            labelMessage.Size = new Size(400, 40);
            labelMessage.TabIndex = 6;
            labelMessage.TextAlign = ContentAlignment.MiddleCenter;
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(30, 30, 30);
            ClientSize = new Size(800, 450);
            Controls.Add(labelMessage);
            Controls.Add(labelWelcome);
            Controls.Add(labelStatus);
            Controls.Add(panelLogin);
            Controls.Add(panelLeft);
            FormBorderStyle = FormBorderStyle.FixedSingle;
            MaximizeBox = false;
            Name = "Form1";
            Text = "ProMag Steam Games";
            Load += Form1_Load;
            panelLeft.ResumeLayout(false);
            panelLogin.ResumeLayout(false);
            panelLogin.PerformLayout();
            ResumeLayout(false);
        }

        private System.Windows.Forms.Panel panelLeft;
        private System.Windows.Forms.Button btnSettings;
        private System.Windows.Forms.Button btnHistory;
        private System.Windows.Forms.Button btnPackages;
        private System.Windows.Forms.Button btnAllGames;
        private System.Windows.Forms.Panel panelLogin;
        private System.Windows.Forms.CheckBox chkRememberMe;
        private System.Windows.Forms.Button btnRegister;
        private System.Windows.Forms.Button btnLogin;
        private System.Windows.Forms.TextBox txtPassword;
        private System.Windows.Forms.TextBox txtUsername;
        private System.Windows.Forms.Label labelStatus;
        private System.Windows.Forms.Label labelWelcome;
        private System.Windows.Forms.Button btnLogout;
        private System.Windows.Forms.Label labelMessage;
    }
}